clear; clc; close all;
global speed
var1 = optimizableVariable('Left_ExtPeakTiming',[0.35 0.6]);
var2 = optimizableVariable('Left_FlexPeakTiming',[0.75 1.15]);
var3 = optimizableVariable('Right_ExtPeakTiming',[0.35 0.6]);
var4 = optimizableVariable('Right_FlexPeakTiming',[0.75 1.15]);

LeftExtMag = 6;
LeftFlexMag = -6;
RightExtMag = 6;
RightFlexMag = -6;

InitLoop = 0;

% 'PlotFcn',@plotConstraintModels...
% );

while true
%     pause(0.1);
    close all;
    speed = rand(1);
    
    if InitLoop == 0
        BayesObject = bayesopt(@testFcn,[var1 var2 var3 var4],...
        'AcquisitionFunction','expected-improvement-per-second-plus',...
        'IsObjectiveDeterministic', 0,...
        'OutputFcn',@assignInBase,...
        'MaxObjectiveEvaluations',1,...
        'PlotFcn',[],...
        'verbose',0);
        InitLoop = 1;
    else
        BayesObject = resume(BayesObject,...
        'MaxObjectiveEvaluations',1,...
        'IsObjectiveDeterministic', 0,...
        'OutputFcn',@assignInBase,...
        'PlotFcn',[],...
        'verbose',0);
    end

    currentParam = BayesObject.XTrace(end,:);
    paramSet = strcat('v',...
                      num2str(LeftExtMag),',',...
                      num2str(LeftFlexMag),',',...
                      num2str(0.3),',',...
                      num2str(currentParam.Left_ExtPeakTiming),',',...
                      num2str(0.65),',',...
                      num2str(0.7),',',...
                      num2str(currentParam.Left_FlexPeakTiming),',',...
                      num2str(1.2),',',...
                      num2str(RightExtMag),',',...
                      num2str(RightFlexMag),',',...       
                      num2str(0.3),',',...
                      num2str(currentParam.Right_ExtPeakTiming),',',...
                      num2str(0.65),',',...
                      num2str(0.7),',',...                     
                      num2str(currentParam.Right_FlexPeakTiming),',',...
                      num2str(1.2),'!');
     fprintf('Current IterNum: ')             
     fprintf("%d",BayesObject.NumObjectiveEvaluations)
     fprintf(', Speed: ')             
     fprintf("%f",speed)
     fprintf( '\n' );                  
     fprintf("%s",paramSet)
     fprintf( '\n' );
     fprintf( '\n' );
end

function ObjFcn = testFcn(x)
global speed
ObjFcn = -speed;
end

